model:
  name: hrnet
  frames_in: 3
  frames_out: 3
  inp_height: 288
  inp_width: 512
  out_height: 288
  out_width: 512
  rgb_diff: False
  out_scales: [0]
  MODEL:
    EXTRA:
      FINAL_CONV_KERNEL: 1
      PRETRAINED_LAYERS: ['*']
      STEM:
        INPLANES: 64
        STRIDES: [1,1]
      STAGE1:
        NUM_MODULES: 1
        NUM_BRANCHES: 1
        BLOCK: BOTTLENECK
        NUM_BLOCKS: [1]
        NUM_CHANNELS: [32]
        FUSE_METHOD: SUM
      STAGE2:
        NUM_MODULES: 1
        NUM_BRANCHES: 2
        BLOCK: BASIC
        NUM_BLOCKS: [2,2]
        NUM_CHANNELS: [16,32]
        FUSE_METHOD: SUM
      STAGE3:
        NUM_MODULES: 1
        NUM_BRANCHES: 3
        BLOCK: BASIC
        NUM_BLOCKS: [2,2,2]
        NUM_CHANNELS: [16,32,64]
        FUSE_METHOD: SUM
      STAGE4:
        NUM_MODULES: 1
        NUM_BRANCHES: 4
        BLOCK: BASIC
        NUM_BLOCKS: [2,2,2,2]
        NUM_CHANNELS: [16,32,64,128]
        FUSE_METHOD: SUM
      DECONV:
        NUM_DECONVS: 0
        KERNEL_SIZE: []
        NUM_BASIC_BLOCKS: 2
    INIT_WEIGHTS: True

detector:
  defaults:
          - _self_
  name: tracknetv2
  model_path: # None
  step: 3
  postprocessor:
    name: tracknetv2
    score_threshold: 0.5
    scales: [0]
    blob_det_method: concomp
    use_hm_weight: True

tracker:
  name: online
  max_disp: 300

runner:
  name: eval
  device: cuda
  gpus: [0,1,2,3]
  vis_result: False
  vis_hm: False
  vis_traj: False
  # best_model_name: wasb_tennis_best.pth
  # model_dir: 
  # model_path: /weights/
  split: test
  fp1_filename: # dummy
  eval:
    score_threshold: 0.5
    dist_threshold: 4

dataloader:
      heatmap:
        sigmas: [2.5]

heatmap:
        name: binary_fixed_size
        sigmas: [2.5]
        mags: [1.0]
        min_value: 0.6


model_path: /weights/wasb_tennis_best.pth  # Adjust to your model path
socket_url: wss://jason-shawjaine.top:8086/general
cap_url: http://jason-shawjaine.top:7001/tennisVideo